function Max_Passengers = importMaxPassengers(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   Max_Passengers = IMPORTFILE(FILE) reads data from the first worksheet
%   in the Microsoft Excel spreadsheet file named FILE and returns the data
%   as column vectors.
%
%   Max_Passengers = IMPORTFILE(FILE,SHEET) reads from the specified
%   worksheet.
%
%   Max_Passengers = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the
%   specified worksheet for the specified row interval(s). Specify STARTROW
%   and ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   Max_Passengers = importfile('Data Set - Vuelos - Completo - Prueba.xlsx','DM_Avion',1,175);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/11/25 23:12:17

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 175;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Max_Passengers = data(:,1);

