function [AirportID,Latitude,Longitude,Timezone] = importfileAirportInfo(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [AirportID1,Latitude1,Longitude1,Timezone] = IMPORTFILE(FILE) reads
%   data from the first worksheet in the Microsoft Excel spreadsheet file
%   named FILE and returns the data as column vectors.
%
%   [AirportID1,Latitude1,Longitude1,Timezone] = IMPORTFILE(FILE,SHEET)
%   reads from the specified worksheet.
%
%   [AirportID1,Latitude1,Longitude1,Timezone] =
%   IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [AirportID1,Latitude1,Longitude1,Timezone] = importfile('Data Set - Vuelos.xlsx','Airports',1,10669);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/11/13 18:27:11

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 10669;
end

%% Import the data
[~, ~, raw1] = xlsread(workbookFile, sheetName, sprintf('A%d:A%d',startRow(1),endRow(1)));
[~, ~, raw2] = xlsread(workbookFile, sheetName, sprintf('G%d:H%d',startRow(1),endRow(1)));
[~, ~, raw3] = xlsread(workbookFile, sheetName, sprintf('J%d:J%d',startRow(1),endRow(1)));
raw = [raw1,raw2,raw3];
for block=2:length(startRow)
    [~, ~, tmpRawBlock1] = xlsread(workbookFile, sheetName, sprintf('A%d:A%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock2] = xlsread(workbookFile, sheetName, sprintf('G%d:H%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock3] = xlsread(workbookFile, sheetName, sprintf('J%d:J%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock1,tmpRawBlock2,tmpRawBlock3]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4]);

%% Allocate imported array to column variable names
AirportID = cellVectors(:,1);
Latitude = cellVectors(:,2);
Longitude = cellVectors(:,3);
Timezone = cellVectors(:,4);