function [SK_Aerolinea,SK_Aeropuerto_Origen,SK_Aeropuerto_Destino,SK_Avion] = importfileRouteInfo(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [SK_Aerolinea,SK_Aeropuerto_Origen,SK_Aeropuerto_Destino,SK_Avion] =
%   IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [SK_Aerolinea,SK_Aeropuerto_Origen,SK_Aeropuerto_Destino,SK_Avion] =
%   IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [SK_Aerolinea,SK_Aeropuerto_Origen,SK_Aeropuerto_Destino,SK_Avion] =
%   IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [SK_Aerolinea,SK_Aeropuerto_Origen,SK_Aeropuerto_Destino,SK_Avion] = importfile('Data Set - Vuelos - Completo.xlsx','DM_Ruta',1,67664);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2018/11/24 12:42:51

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 67664;
end

%% Import the data
[~, ~, raw1] = xlsread(workbookFile, sheetName, sprintf('A%d:A%d',startRow(1),endRow(1)));
[~, ~, raw2] = xlsread(workbookFile, sheetName, sprintf('C%d:C%d',startRow(1),endRow(1)));
[~, ~, raw3] = xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(1),endRow(1)));
[~, ~, raw4] = xlsread(workbookFile, sheetName, sprintf('G%d:G%d',startRow(1),endRow(1)));
raw = [raw1,raw2,raw3,raw4];
for block=2:length(startRow)
    [~, ~, tmpRawBlock1] = xlsread(workbookFile, sheetName, sprintf('A%d:A%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock2] = xlsread(workbookFile, sheetName, sprintf('C%d:C%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock3] = xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock4] = xlsread(workbookFile, sheetName, sprintf('G%d:G%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock1,tmpRawBlock2,tmpRawBlock3,tmpRawBlock4]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4]);

%% Allocate imported array to column variable names
SK_Aerolinea = cellVectors(:,1);
SK_Aeropuerto_Origen = cellVectors(:,2);
SK_Aeropuerto_Destino = cellVectors(:,3);
SK_Avion = cellVectors(:,4);

