%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Flor\Documents\BI\TP\Data Set - Vuelos.xlsx
%    Worksheet: Planes
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/24 05:12:34

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Flor\Documents\BI\TP\Data Set - Vuelos.xlsx','Planes','B2:B175');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);

%% Allocate imported array to column variable names
IATACode = cellVectors(:,1);

%% Clear temporary variables
clearvars raw cellVectors;

%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Flor\Documents\BI\TP\Data Set - Vuelos.xlsx
%    Worksheet: Routs
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/24 05:13:32

%% Import the data
[~, ~, raw] = xlsread('C:\Users\Flor\Documents\BI\TP\Data Set - Vuelos.xlsx','Routs','I2:I67664');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);

%% Allocate imported array to column variable names
Equipment = cellVectors(:,1);

%% Clear temporary variables
clearvars raw cellVectors;

Codigo_IATA=IATACode;
Avion=Equipment;

AUX=nan(length(Avion),1);
for i=1:length(Avion)
    try
        if(ismember(Avion{i}(1:3),Codigo_IATA))
            [~,AUX(i,1)]=ismember(Avion{i}(1:3),Codigo_IATA);
        end
    catch
    end
end